# -*- coding: utf-8 -*-
"""
Created on Mon Aug 30 11:52:13 2021

@author: alper
"""
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'versiyon2.1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(854, 600)
        MainWindow.setMaximumSize(QtCore.QSize(900, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QtCore.QSize(450, 300))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.GIRISs = QtWidgets.QWidget()
        self.GIRISs.setObjectName("GIRISs")
        self.label_10 = QtWidgets.QLabel(self.GIRISs)
        self.label_10.setGeometry(QtCore.QRect(10, 230, 351, 21))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.groupBox = QtWidgets.QGroupBox(self.GIRISs)
        self.groupBox.setGeometry(QtCore.QRect(20, 110, 311, 171))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lneKayitAdSoyad = QtWidgets.QLineEdit(self.groupBox)
        self.lneKayitAdSoyad.setInputMask("")
        self.lneKayitAdSoyad.setMaxLength(30)
        self.lneKayitAdSoyad.setObjectName("lneKayitAdSoyad")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lneKayitAdSoyad)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lneKayitKullaniciAdi = QtWidgets.QLineEdit(self.groupBox)
        self.lneKayitKullaniciAdi.setMaxLength(20)
        self.lneKayitKullaniciAdi.setObjectName("lneKayitKullaniciAdi")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lneKayitKullaniciAdi)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lneKayitSifre = QtWidgets.QLineEdit(self.groupBox)
        self.lneKayitSifre.setMaxLength(10)
        self.lneKayitSifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lneKayitSifre.setObjectName("lneKayitSifre")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lneKayitSifre)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.label_11 = QtWidgets.QLabel(self.GIRISs)
        self.label_11.setGeometry(QtCore.QRect(30, 290, 161, 31))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.groupBox_2 = QtWidgets.QGroupBox(self.GIRISs)
        self.groupBox_2.setGeometry(QtCore.QRect(470, 110, 311, 171))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 50, 271, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lneGirisKullaniciAdi = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lneGirisKullaniciAdi.setMaxLength(20)
        self.lneGirisKullaniciAdi.setObjectName("lneGirisKullaniciAdi")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lneGirisKullaniciAdi)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lneGirisSifre = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lneGirisSifre.setMaxLength(10)
        self.lneGirisSifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lneGirisSifre.setObjectName("lneGirisSifre")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lneGirisSifre)
        self.btnGirisYap = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnGirisYap.setObjectName("btnGirisYap")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btnGirisYap)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 281, 41))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.GIRISs)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.GIRISs)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 330, 651, 131))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.btnEkle = QtWidgets.QPushButton(self.groupBox_3)
        self.btnEkle.setGeometry(QtCore.QRect(570, 100, 71, 28))
        self.btnEkle.setObjectName("btnEkle")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(15, 10, 541, 121))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.lneKonu = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.lneKonu.setObjectName("lneKonu")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lneKonu)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.spnGunlukHedef = QtWidgets.QSpinBox(self.formLayoutWidget_5)
        self.spnGunlukHedef.setMinimum(1)
        self.spnGunlukHedef.setObjectName("spnGunlukHedef")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spnGunlukHedef)
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.spnGunlukDK = QtWidgets.QSpinBox(self.formLayoutWidget_5)
        self.spnGunlukDK.setSpecialValueText("")
        self.spnGunlukDK.setMaximum(500)
        self.spnGunlukDK.setSingleStep(2)
        self.spnGunlukDK.setProperty("value", 30)
        self.spnGunlukDK.setObjectName("spnGunlukDK")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spnGunlukDK)
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.spnOnemPuan = QtWidgets.QSpinBox(self.formLayoutWidget_5)
        self.spnOnemPuan.setMinimum(1)
        self.spnOnemPuan.setMaximum(5)
        self.spnOnemPuan.setObjectName("spnOnemPuan")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spnOnemPuan)
        self.label_24 = QtWidgets.QLabel(self.GIRISs)
        self.label_24.setGeometry(QtCore.QRect(180, 20, 411, 61))
        font = QtGui.QFont()
        font.setFamily("Ink Free")
        font.setPointSize(25)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.btnKaydet = QtWidgets.QPushButton(self.GIRISs)
        self.btnKaydet.setGeometry(QtCore.QRect(700, 450, 101, 41))
        self.btnKaydet.setObjectName("btnKaydet")
        self.tabWidget.addTab(self.GIRISs, "")
        self.ekleme = QtWidgets.QWidget()
        self.ekleme.setEnabled(False)
        self.ekleme.setObjectName("ekleme")
        self.label_9 = QtWidgets.QLabel(self.ekleme)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 271, 51))
        font = QtGui.QFont()
        font.setFamily("MingLiU-ExtB")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.cmbKonular = QtWidgets.QComboBox(self.ekleme)
        self.cmbKonular.setGeometry(QtCore.QRect(310, 10, 231, 51))
        self.cmbKonular.setObjectName("cmbKonular")
        self.cmbKonular.addItem("")
        self.chkIlgilenmedim = QtWidgets.QCheckBox(self.ekleme)
        self.chkIlgilenmedim.setGeometry(QtCore.QRect(580, 20, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Candara Light")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.chkIlgilenmedim.setFont(font)
        self.chkIlgilenmedim.setObjectName("chkIlgilenmedim")
        self.btnKaydet_2 = QtWidgets.QPushButton(self.ekleme)
        self.btnKaydet_2.setGeometry(QtCore.QRect(650, 170, 101, 41))
        self.btnKaydet_2.setObjectName("btnKaydet_2")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.ekleme)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(30, 80, 565, 131))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_28 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_4.addWidget(self.label_28)
        self.spnGunlukDK_2 = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.spnGunlukDK_2.setSpecialValueText("")
        self.spnGunlukDK_2.setMinimum(0)
        self.spnGunlukDK_2.setMaximum(5)
        self.spnGunlukDK_2.setSingleStep(1)
        self.spnGunlukDK_2.setProperty("value", 2)
        self.spnGunlukDK_2.setObjectName("spnGunlukDK_2")
        self.horizontalLayout_4.addWidget(self.spnGunlukDK_2)
        self.formLayout_8.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_40 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_5.addWidget(self.label_40)
        self.spnYarinHedef = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.spnYarinHedef.setSpecialValueText("")
        self.spnYarinHedef.setMaximum(500)
        self.spnYarinHedef.setSingleStep(2)
        self.spnYarinHedef.setProperty("value", 30)
        self.spnYarinHedef.setObjectName("spnYarinHedef")
        self.horizontalLayout_5.addWidget(self.spnYarinHedef)
        self.formLayout_8.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_5)
        self.label_42 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.spnGunlukDK_7 = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.spnGunlukDK_7.setSpecialValueText("")
        self.spnGunlukDK_7.setMaximum(500)
        self.spnGunlukDK_7.setSingleStep(2)
        self.spnGunlukDK_7.setProperty("value", 30)
        self.spnGunlukDK_7.setObjectName("spnGunlukDK_7")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spnGunlukDK_7)
        self.line = QtWidgets.QFrame(self.ekleme)
        self.line.setGeometry(QtCore.QRect(10, 230, 811, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_41 = QtWidgets.QLabel(self.ekleme)
        self.label_41.setGeometry(QtCore.QRect(10, 240, 201, 51))
        font = QtGui.QFont()
        font.setFamily("MingLiU-ExtB")
        font.setPointSize(18)
        font.setKerning(True)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.btnBitir = QtWidgets.QPushButton(self.ekleme)
        self.btnBitir.setGeometry(QtCore.QRect(720, 480, 101, 41))
        self.btnBitir.setObjectName("btnBitir")
        self.btnBilgiler = QtWidgets.QPushButton(self.ekleme)
        self.btnBilgiler.setGeometry(QtCore.QRect(590, 480, 101, 41))
        self.btnBilgiler.setObjectName("btnBilgiler")
        self.lbBaslikKonu = QtWidgets.QLabel(self.ekleme)
        self.lbBaslikKonu.setGeometry(QtCore.QRect(280, 240, 151, 51))
        font = QtGui.QFont()
        font.setFamily("MingLiU-ExtB")
        font.setPointSize(15)
        font.setItalic(True)
        font.setKerning(True)
        self.lbBaslikKonu.setFont(font)
        self.lbBaslikKonu.setObjectName("lbBaslikKonu")
        self.progKalan = QtWidgets.QProgressBar(self.ekleme)
        self.progKalan.setGeometry(QtCore.QRect(20, 440, 291, 71))
        self.progKalan.setProperty("value", 0)
        self.progKalan.setOrientation(QtCore.Qt.Horizontal)
        self.progKalan.setObjectName("progKalan")
        self.lbGrafik = QtWidgets.QLabel(self.ekleme)
        self.lbGrafik.setGeometry(QtCore.QRect(420, 250, 391, 221))
        self.lbGrafik.setObjectName("lbGrafik")
        self.layoutWidget = QtWidgets.QWidget(self.ekleme)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 290, 356, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbToplamHedef = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(11)
        self.lbToplamHedef.setFont(font)
        self.lbToplamHedef.setObjectName("lbToplamHedef")
        self.verticalLayout.addWidget(self.lbToplamHedef)
        self.lbKalanGun = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(11)
        self.lbKalanGun.setFont(font)
        self.lbKalanGun.setObjectName("lbKalanGun")
        self.verticalLayout.addWidget(self.lbKalanGun)
        self.lbKalanDK = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbKalanDK.setFont(font)
        self.lbKalanDK.setObjectName("lbKalanDK")
        self.verticalLayout.addWidget(self.lbKalanDK)
        self.lbGununPuani = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.lbGununPuani.setFont(font)
        self.lbGununPuani.setObjectName("lbGununPuani")
        self.verticalLayout.addWidget(self.lbGununPuani)
        self.tabWidget.addTab(self.ekleme, "")
        self.BILGILER = QtWidgets.QWidget()
        self.BILGILER.setObjectName("BILGILER")
        self.tbwHedefler = QtWidgets.QTableWidget(self.BILGILER)
        self.tbwHedefler.setGeometry(QtCore.QRect(0, 270, 821, 101))
        self.tbwHedefler.setObjectName("tbwHedefler")
        self.tbwHedefler.setColumnCount(5)
        self.tbwHedefler.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tbwHedefler.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwHedefler.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwHedefler.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwHedefler.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwHedefler.setHorizontalHeaderItem(4, item)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.BILGILER)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 361, 143))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.lbBilgiIsim = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.lbBilgiIsim.setFont(font)
        self.lbBilgiIsim.setObjectName("lbBilgiIsim")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbBilgiIsim)
        self.lbBilgiKullanici = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.lbBilgiKullanici.setFont(font)
        self.lbBilgiKullanici.setObjectName("lbBilgiKullanici")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbBilgiKullanici)
        self.lbBilgiSifre = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.lbBilgiSifre.setFont(font)
        self.lbBilgiSifre.setObjectName("lbBilgiSifre")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbBilgiSifre)
        self.lbBilgiToplamPuan = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.lbBilgiToplamPuan.setFont(font)
        self.lbBilgiToplamPuan.setObjectName("lbBilgiToplamPuan")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbBilgiToplamPuan)
        self.tbwTamamlananlar = QtWidgets.QTableWidget(self.BILGILER)
        self.tbwTamamlananlar.setGeometry(QtCore.QRect(0, 430, 821, 91))
        self.tbwTamamlananlar.setObjectName("tbwTamamlananlar")
        self.tbwTamamlananlar.setColumnCount(5)
        self.tbwTamamlananlar.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tbwTamamlananlar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwTamamlananlar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwTamamlananlar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwTamamlananlar.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwTamamlananlar.setHorizontalHeaderItem(4, item)
        self.label_16 = QtWidgets.QLabel(self.BILGILER)
        self.label_16.setGeometry(QtCore.QRect(10, 230, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.BILGILER)
        self.label_17.setGeometry(QtCore.QRect(0, 380, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.btnCikis = QtWidgets.QPushButton(self.BILGILER)
        self.btnCikis.setGeometry(QtCore.QRect(260, 170, 91, 31))
        self.btnCikis.setObjectName("btnCikis")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.BILGILER)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(380, 50, 441, 168))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_29 = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.lneBilgiKonu = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.lneBilgiKonu.setObjectName("lneBilgiKonu")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lneBilgiKonu)
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.spnBilgiGunlukHedef = QtWidgets.QSpinBox(self.formLayoutWidget_6)
        self.spnBilgiGunlukHedef.setMinimum(1)
        self.spnBilgiGunlukHedef.setObjectName("spnBilgiGunlukHedef")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spnBilgiGunlukHedef)
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.spnBilgiGunlukDK = QtWidgets.QSpinBox(self.formLayoutWidget_6)
        self.spnBilgiGunlukDK.setSpecialValueText("")
        self.spnBilgiGunlukDK.setMaximum(500)
        self.spnBilgiGunlukDK.setSingleStep(2)
        self.spnBilgiGunlukDK.setProperty("value", 30)
        self.spnBilgiGunlukDK.setObjectName("spnBilgiGunlukDK")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spnBilgiGunlukDK)
        self.label_32 = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(9)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.spnBilgiOnemPuan = QtWidgets.QSpinBox(self.formLayoutWidget_6)
        self.spnBilgiOnemPuan.setMinimum(1)
        self.spnBilgiOnemPuan.setMaximum(5)
        self.spnBilgiOnemPuan.setObjectName("spnBilgiOnemPuan")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spnBilgiOnemPuan)
        self.btnBilgiEkle = QtWidgets.QPushButton(self.formLayoutWidget_6)
        self.btnBilgiEkle.setObjectName("btnBilgiEkle")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.btnBilgiEkle)
        self.label_18 = QtWidgets.QLabel(self.BILGILER)
        self.label_18.setGeometry(QtCore.QRect(380, 0, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Modern")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.tabWidget.addTab(self.BILGILER, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Sizi taniyalim"))
        self.label_6.setText(_translate("MainWindow", "Adiniz ve Soyadiniz:"))
        self.label_7.setText(_translate("MainWindow", "Kullanici adiniz"))
        self.label_8.setText(_translate("MainWindow", "Sifreniz"))
        self.label_11.setText(_translate("MainWindow", "Hemen baslayalim"))
        self.label.setText(_translate("MainWindow", "Kullanici adiniz:"))
        self.label_2.setText(_translate("MainWindow", "Sifreniz:"))
        self.btnGirisYap.setText(_translate("MainWindow", "GIRIS YAP"))
        self.label_4.setText(_translate("MainWindow", "YOKSA BIR HESABA SAHIP MISINIZ?"))
        self.label_3.setText(_translate("MainWindow", "HOSGELDINIZ"))
        self.btnEkle.setText(_translate("MainWindow", "EKLE"))
        self.label_23.setText(_translate("MainWindow", "Lutfen gunluk geliseceginiz bir konuyu girin"))
        self.label_25.setText(_translate("MainWindow", "Bu HEDEF\'e ulasmak icin kac gun gerekir?"))
        self.label_26.setText(_translate("MainWindow", "Peki gunde kac Dakika calismaliyiz?"))
        self.spnGunlukDK.setSuffix(_translate("MainWindow", " DK"))
        self.label_27.setText(_translate("MainWindow", "Bu hedefe 1-5 arasinda onem puani veriniz"))
        self.label_24.setText(_translate("MainWindow", "     BASARACAGIM"))
        self.btnKaydet.setText(_translate("MainWindow", "KAYDET"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GIRISs), _translate("MainWindow", "GIRIS"))
        self.label_9.setText(_translate("MainWindow", "Bugun ne yaptim?"))
        self.cmbKonular.setItemText(0, _translate("MainWindow",''))
        self.chkIlgilenmedim.setText(_translate("MainWindow", "Bu Konuyla ilgilenemedim:(("))
        self.btnKaydet_2.setText(_translate("MainWindow", "KAYDET"))
        self.label_28.setText(_translate("MainWindow", "Sence ne kadar verimli id i? [1-5]"))
        self.spnGunlukDK_2.setSuffix(_translate("MainWindow", ""))
        self.label_40.setText(_translate("MainWindow", "Yarin ne kadar calisacagiz?"))
        self.spnYarinHedef.setSuffix(_translate("MainWindow", " DK"))
        self.label_42.setText(_translate("MainWindow", "Bugun kac Dakika calistik?"))
        self.spnGunlukDK_7.setSuffix(_translate("MainWindow", " DK"))
        self.label_41.setText(_translate("MainWindow", "Sonuclar :))"))
        self.btnBitir.setText(_translate("MainWindow", "BITIR [X]"))
        self.btnBilgiler.setText(_translate("MainWindow", "BILGILER"))
        self.lbBaslikKonu.setText(_translate("MainWindow", "konu"))
        self.lbGrafik.setText(_translate("MainWindow", "grafik or ozlusoz"))
        self.lbToplamHedef.setText(_translate("MainWindow", "Toplam hedefimiz ... GUN"))
        self.lbKalanGun.setText(_translate("MainWindow", "Hedefe ulasmaya ... gun kaldi"))
        self.lbKalanDK.setText(_translate("MainWindow", "Hedefe ulasmak icin ... dakika daha calisacagiz"))
        self.lbGununPuani.setText(_translate("MainWindow", "GUNUN PUANI:        "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ekleme), _translate("MainWindow", "EKLE"))
        item = self.tbwHedefler.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "HEDEF"))
        item = self.tbwHedefler.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "KAC GUN"))
        item = self.tbwHedefler.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "GUNLUK HEDEF"))
        item = self.tbwHedefler.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ONEMI"))
        item = self.tbwHedefler.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "KAYIT"))
        self.label_12.setText(_translate("MainWindow", "ISIM VE SOYISIM:"))
        self.label_13.setText(_translate("MainWindow", "KULLANICI ADI"))
        self.label_14.setText(_translate("MainWindow", "SIFRE"))
        self.label_15.setText(_translate("MainWindow", "TOPLAM PUAN"))
        self.lbBilgiIsim.setText(_translate("MainWindow", "alperen celik"))
        self.lbBilgiKullanici.setText(_translate("MainWindow", "alperen celik"))
        self.lbBilgiSifre.setText(_translate("MainWindow", "alperen celik"))
        self.lbBilgiToplamPuan.setText(_translate("MainWindow", ""))
        item = self.tbwTamamlananlar.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "HEDEF"))
        item = self.tbwTamamlananlar.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "KAC GUN"))
        item = self.tbwTamamlananlar.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TOPLAM DAKIKA"))
        item = self.tbwTamamlananlar.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "BITIRME TARIHI"))
        item = self.tbwTamamlananlar.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ILK KAYIT"))
        self.label_16.setText(_translate("MainWindow", "HEDEFLER TABLOSU"))
        self.label_17.setText(_translate("MainWindow", "TAMAMLANANLAR TABLOSU"))
        self.btnCikis.setText(_translate("MainWindow", "CIKIS"))
        self.label_29.setText(_translate("MainWindow", "Lutfen gunluk geliseceginiz bir konuyu girin"))
        self.label_30.setText(_translate("MainWindow", "Bu HEDEF\'e ulasmak icin kac gun gerekir?"))
        self.label_31.setText(_translate("MainWindow", "Peki gunde kac Dakika calismaliyiz?"))
        self.spnBilgiGunlukDK.setSuffix(_translate("MainWindow", " DK"))
        self.label_32.setText(_translate("MainWindow", "Bu hedefe 1-5 arasinda onem puani veriniz"))
        self.btnBilgiEkle.setText(_translate("MainWindow", "EKLE"))
        self.label_18.setText(_translate("MainWindow", "Yeni Hedef ekle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BILGILER), _translate("MainWindow", "BILGILER"))

